services:
  database1:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    container_name: trip-note
    environment:
      POSTGRES_USER: "user"
      POSTGRES_DB: "db"
      POSTGRES_PASSWORD: "password"
